AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla para desplegar recursos en AWS

Resources:
  VPCCl6C4B:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: VPCCl6C4B

  SubnetCl6C4B:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCCl6C4B
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-2a
      Tags:
        - Key: Name
          Value: SubnetCl6C4B

  IGCl6C4B:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGCl6C4B

  VPCGACl6C4B:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCCl6C4B
      InternetGatewayId: !Ref IGCl6C4B

  RTCl6C4B:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCCl6C4B
      Tags:
        - Key: Name
          Value: RTCl6C4B

  RCl6C4B:
    Type: AWS::EC2::Route
    DependsOn: VPCGACl6C4B
    Properties:
      RouteTableId: !Ref RTCl6C4B
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGCl6C4B

  SRTACl6C4B:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetCl6C4B
      RouteTableId: !Ref RTCl6C4B

  SGPCl6C4B:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP traffic
      VpcId: !Ref VPCCl6C4B
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ProductionInstanceCl6C4B:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-024e6efaf93d85776
      InstanceType: t2.micro
      KeyName: Clase6C4B
      SubnetId: !Ref SubnetCl6C4B
      SecurityGroupIds:
        - !Ref SGPCl6C4B
      Tags:
        - Key: Name
          Value: ProductionInstanceCl6C4B

  TestingInstanceCl6C4B:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-024e6efaf93d85776
      InstanceType: t2.micro
      KeyName: Clase6C4B
      SubnetId: !Ref SubnetCl6C4B
      SecurityGroupIds:
        - !Ref SGPCl6C4B
      Tags:
        - Key: Name
          Value: TestingInstanceCl6C4B

  DevelopmentInstanceCl6C4B:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05d8140b845a8aa7b
      InstanceType: t1.micro
      KeyName: Clase6C4B
      SubnetId: !Ref SubnetCl6C4B
      SecurityGroupIds:
        - !Ref SGPCl6C4B
      Tags:
        - Key: Name
          Value: DevelopmentInstanceCl6C4B
